In [17]:
import numpy as np

# Constants from the Ising model adapted for Go
J_ally = 1    # Interaction strength between allied stones
J_enemy = -1   # Interaction strength between enemy stones

# Define the size of the Go board (standard is 19x19)
N = 9  # Go board size

# Initialize the Go board with zeros (empty board)
go_board = np.zeros((N, N), dtype=int)

# Helper function to find the group of stones connected to the stone at (i, j)
def find_group(board, i, j, color, visited):
    """
    Find all stones connected to the stone at (i, j) and return their positions.
    """
    if (i, j) in visited or board[i, j] != color:
        return [], visited

    visited.add((i, j))
    group = [(i, j)]
    if i > 0:
        new_group, visited = find_group(board, i-1, j, color, visited)
        group.extend(new_group)
    if i < N-1:
        new_group, visited = find_group(board, i+1, j, color, visited)
        group.extend(new_group)
    if j > 0:
        new_group, visited = find_group(board, i, j-1, color, visited)
        group.extend(new_group)
    if j < N-1:
        new_group, visited = find_group(board, i, j+1, color, visited)
        group.extend(new_group)
    return group, visited

# Helper function to count liberties of a group of stones
def count_liberties(board, group):
    """
    Count the number of liberties (empty adjacent intersections) for the group of stones.
    """
    liberties = set()
    for i, j in group:
        if i > 0 and board[i-1, j] == 0:
            liberties.add((i-1, j))
        if i < N-1 and board[i+1, j] == 0:
            liberties.add((i+1, j))
        if j > 0 and board[i, j-1] == 0:
            liberties.add((i, j-1))
        if j < N-1 and board[i, j+1] == 0:
            liberties.add((i, j+1))
    return len(liberties)

# Function to calculate the energy of the Go board configuration
def go_energy(board, J_ally, J_enemy):
    energy = 0
    visited = set()
    for i in range(N):
        for j in range(N):
            if (i, j) not in visited and board[i, j] != 0:
                group, visited = find_group(board, i, j, board[i, j], visited)
                group_liberties = count_liberties(board, group)
                # Add the group's contribution to the total energy
                energy += J_ally * len(group) - J_enemy * group_liberties
    return energy

# Example Go board configuration (1 for white, -1 for black, 0 for empty)
go_board[0, 0] = 1
go_board[0, 1] = -1
go_board[1, 0] = -1
go_board[1, 1] = 1
go_board[0, 0] = 1
go_board[0, 3] = -1
go_board[3, 0] = -1
go_board[3, 3] = 1
# Calculate the energy of the sample configuration
energy = go_energy(go_board, J_ally, J_enemy)
print(f"The energy of the Go board configuration is: {energy}")

# Output the board to visualize the current state
print("Current board configuration:")
print(go_board)


The energy of the Go board configuration is: 21
Current board configuration:
[[ 1 -1  0 -1  0  0  0  0  0]
 [-1  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [-1  0  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


In [18]:
import numpy as np

# Constants from the Ising model adapted for Go
J_ally = 1    # Interaction strength between allied stones
J_enemy = -1   # Interaction strength between enemy stones

# Define the size of the Go board (standard is 19x19)
N = 9  # Go board size

# Initialize the Go board with zeros (empty board)
go_board = np.zeros((N, N), dtype=int)

# Helper function to find the group of stones connected to the stone at (i, j)
def find_group(board, i, j, color, visited):
    # ... (The function remains unchanged, make sure it's properly indented)

# Helper function to count liberties of a group of stones
def count_liberties(board, group):
    # ... (The function remains unchanged, make sure it's properly indented)

# Function to calculate the energy of the Go board configuration for black and white stones separately
def go_energy(board, J_ally, J_enemy):
    energy_black = 0
    energy_white = 0
    visited = set()
    for i in range(N):
        for j in range(N):
            if (i, j) not in visited and board[i, j] != 0:
                group, visited = find_group(board, i, j, board[i, j], visited)
                group_liberties = count_liberties(board, group)
                # Check the color of the group and add its contribution to the corresponding energy
                if board[i, j] == 1:  # White stones
                    energy_white += J_ally * len(group) - J_enemy * group_liberties
                else:  # Black stones
                    energy_black += J_ally * len(group) - J_enemy * group_liberties
    return energy_black, energy_white

# Example Go board configuration (1 for white, -1 for black, 0 for empty)
go_board[0, 0] = 1
go_board[0, 1] = -1
go_board[1, 0] = -1
go_board[1, 1] = 1
# The next line is redundant since (0, 0) is already set to 1 above, so it can be removed
# go_board[0, 0] = 1
go_board[0, 3] = -1
go_board[3, 0] = -1
go_board[3, 3] = 1

# Calculate the energy of the sample configuration for black and white stones separately
energy_black, energy_white = go_energy(go_board, J_ally, J_enemy)
print(f"The energy of the black stones is: {energy_black}")
print(f"The energy of the white stones is: {energy_white}")

# Output the board to visualize the current state
print("Current board configuration:")
print(go_board)


IndentationError: expected an indented block (<ipython-input-18-13c3f23f3a9e>, line 18)

In [8]:
import numpy as np

# Constants from the Ising model adapted for Go
J_ally = 1    # Interaction strength between allied stones
J_enemy = -1   # Interaction strength between enemy stones

# Define the size of the Go board (standard is 19x19)
N = 9  # Go board size

# Initialize the Go board with zeros (empty board)
go_board = np.zeros((N, N), dtype=int)

# Helper function to find the group of stones connected to the stone at (i, j)
def find_group(board, i, j, color, visited):
    if (i, j) in visited or board[i, j] != color:
        return [], visited

    visited.add((i, j))
    group = [(i, j)]
    # Check adjacent positions for the same color stone and add to the group
    if i > 0:
        new_group, visited = find_group(board, i-1, j, color, visited)
        group.extend(new_group)
    if i < N-1:
        new_group, visited = find_group(board, i+1, j, color, visited)
        group.extend(new_group)
    if j > 0:
        new_group, visited = find_group(board, i, j-1, color, visited)
        group.extend(new_group)
    if j < N-1:
        new_group, visited = find_group(board, i, j+1, color, visited)
        group.extend(new_group)
    return group, visited

# Helper function to count liberties of a group of stones
def count_liberties(board, group):
    liberties = set()
    # Check adjacent positions for empty spaces and count them as liberties
    for i, j in group:
        if i > 0 and board[i-1, j] == 0:
            liberties.add((i-1, j))
        if i < N-1 and board[i+1, j] == 0:
            liberties.add((i+1, j))
        if j > 0 and board[i, j-1] == 0:
            liberties.add((i, j-1))
        if j < N-1 and board[i, j+1] == 0:
            liberties.add((i, j+1))
    return len(liberties)

# Function to calculate the energy of the Go board configuration for black and white stones separately
def go_energy(board, J_ally, J_enemy):
    energy_black = 0
    energy_white = 0
    visited = set()
    for i in range(N):
        for j in range(N):
            if (i, j) not in visited and board[i, j] != 0:
                group, visited = find_group(board, i, j, board[i, j], visited)
                group_liberties = count_liberties(board, group)
                # Adjust energy contribution based on stone color
                if board[i, j] == 1:  # White stones
                    energy_white += J_ally * len(group) - J_enemy * group_liberties
                elif board[i, j] == -1:  # Black stones
                    energy_black += J_ally * len(group) - J_enemy * group_liberties
    return energy_black, energy_white

# Example Go board configuration (1 for white, -1 for black, 0 for empty)
go_board[0, 0] = 1
go_board[0, 1] = -1
go_board[1, 0] = -1
go_board[1, 1] = 1


# Calculate the energy of the sample configuration for black and white stones separately
energy_black, energy_white = go_energy(go_board, J_ally, J_enemy)
print(f"The energy of the black stones is: {energy_black}")
print(f"The energy of the white stones is: {energy_white}")

# Output the board to visualize the current state
print("Current board configuration:")
print(go_board)


The energy of the black stones is: 4
The energy of the white stones is: 4
Current board configuration:
[[ 1 -1  0  0  0  0  0  0  0]
 [-1  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


In [19]:
pip install sympy


You should consider upgrading via the 'C:\Users\Leonardo\anaconda3\envs\IA\python.exe -m pip install --upgrade pip' command.


In [10]:
import numpy as np
import sympy as sp

# Define symbolic variables for Ising polynomial
J_ally_sym, J_enemy_sym = sp.symbols('J_ally J_enemy')
stone = sp.IndexedBase('s')
liberty = sp.IndexedBase('l')

# ... (rest of the script remains the same)

# Function to calculate the Ising polynomial for the Go board configuration
def ising_polynomial(board, J_ally_sym, J_enemy_sym, stone, liberty):
    polynomial = 0
    for i in range(N):
        for j in range(N):
            if board[i, j] != 0:
                # Use symbolic variables to represent the energy contribution of each stone
                polynomial += J_ally_sym * stone[i, j] - J_enemy_sym * liberty[i, j]
    return polynomial

# Function to check the constraint (no group of stones can have zero liberties)
def check_constraints(board):
    constraints_met = True
    visited = set()
    for i in range(N):
        for j in range(N):
            if board[i, j] != 0 and (i, j) not in visited:
                group, visited = find_group(board, i, j, board[i, j], visited)
                if count_liberties(board, group) == 0:
                    constraints_met = False
                    break
    return constraints_met

# ... (rest of the script remains the same)

# Calculate the Ising polynomial of the sample configuration
ising_poly = ising_polynomial(go_board, J_ally_sym, J_enemy_sym, stone, liberty)
print(f"The Ising polynomial of the Go board configuration is: {ising_poly}")

# Check and print the constraints for the sample configuration
constraints_met = check_constraints(go_board)
print(f"Constraints met: {constraints_met}")

# ... (rest of the script remains the same)


The Ising polynomial of the Go board configuration is: J_ally*s[0, 0] + J_ally*s[0, 1] + J_ally*s[1, 0] + J_ally*s[1, 1] - J_enemy*l[0, 0] - J_enemy*l[0, 1] - J_enemy*l[1, 0] - J_enemy*l[1, 1]
Constraints met: False


In [20]:
import numpy as np
import sympy as sp

# Constants from the Ising model adapted for Go
J_ally = 1    # Interaction strength between allied stones
J_enemy = -1   # Interaction strength between enemy stones

# Define symbolic variables for Ising polynomial
J_ally_sym, J_enemy_sym = sp.symbols('J_ally J_enemy')
stone = sp.IndexedBase('s')
liberty = sp.IndexedBase('l')

# Define the size of the Go board (standard is 19x19)
N = 9  # Go board size

# Initialize the Go board with zeros (empty board)
go_board = np.zeros((N, N), dtype=int)

# Helper function to find the group of stones connected to the stone at (i, j)
def find_group(board, i, j, color, visited):
    # ... (unchanged)

# Helper function to count liberties of a group of stones
def count_liberties(board, group):
    # ... (unchanged)

# Function to calculate the energy of the Go board configuration for black and white stones separately
def go_energy(board, J_ally, J_enemy):
    # ... (unchanged)

# Function to calculate the Ising polynomial for the Go board configuration
def ising_polynomial(board, J_ally_sym, J_enemy_sym, stone, liberty):
    # ... (unchanged)

# Function to check the constraint (no group of stones can have zero liberties)
def check_constraints(board):
    # ... (unchanged)

# Example Go board configuration (1 for white, -1 for black, 0 for empty)
go_board[0, 0] = 1
go_board[0, 1] = -1
go_board[1, 0] = -1
go_board[1, 1] = 1
go_board[0, 3] = -1
go_board[3, 0] = -1
go_board[3, 3] = 1

# Calculate the energy of the sample configuration for black and white stones separately
energy_black, energy_white = go_energy(go_board, J_ally, J_enemy)
print(f"The energy of the black stones is: {energy_black}")
print(f"The energy of the white stones is: {energy_white}")

# Calculate the Ising polynomial of the sample configuration
ising_poly = ising_polynomial(go_board, J_ally_sym, J_enemy_sym, stone, liberty)
print(f"The Ising polynomial of the Go board configuration is: {ising_poly}")

# Check and print the constraints for the sample configuration
constraints_met = check_constraints(go_board)
print(f"Constraints met: {constraints_met}")

# Output the board to visualize the current state
print("Current board configuration:")
print(go_board)


IndentationError: expected an indented block (<ipython-input-20-923c070c79c1>, line 24)

In [14]:
import numpy as np
import sympy as sp

# Constants from the Ising model adapted for Go
J_ally = 1    # Interaction strength between allied stones
J_enemy = -1   # Interaction strength between enemy stones

# Define symbolic variables for Ising polynomial
J_ally_sym, J_enemy_sym = sp.symbols('J_ally J_enemy')
stone = sp.IndexedBase('s')
liberty = sp.IndexedBase('l')

# Define the size of the Go board (standard is 19x19)
N = 5  # Go board size

# Initialize the Go board with zeros (empty board)
go_board = np.zeros((N, N), dtype=int)

# Helper function to find the group of stones connected to the stone at (i, j)
def find_group(board, i, j, color, visited):
    if (i, j) in visited or board[i, j] != color:
        return [], visited

    visited.add((i, j))
    group = [(i, j)]
    # Check adjacent positions for the same color stone and add to the group
    if i > 0:
        new_group, visited = find_group(board, i-1, j, color, visited)
        group.extend(new_group)
    if i < N-1:
        new_group, visited = find_group(board, i+1, j, color, visited)
        group.extend(new_group)
    if j > 0:
        new_group, visited = find_group(board, i, j-1, color, visited)
        group.extend(new_group)
    if j < N-1:
        new_group, visited = find_group(board, i, j+1, color, visited)
        group.extend(new_group)
    return group, visited

# Helper function to count liberties of a group of stones
def count_liberties(board, group):
    liberties = set()
    # Check adjacent positions for empty spaces and count them as liberties
    for i, j in group:
        if i > 0 and board[i-1, j] == 0:
            liberties.add((i-1, j))
        if i < N-1 and board[i+1, j] == 0:
            liberties.add((i+1, j))
        if j > 0 and board[i, j-1] == 0:
            liberties.add((i, j-1))
        if j < N-1 and board[i, j+1] == 0:
            liberties.add((i, j+1))
    return len(liberties)

# Function to calculate the energy of the Go board configuration for black and white stones separately
def go_energy(board, J_ally, J_enemy):
    energy_black = 0
    energy_white = 0
    visited = set()
    for i in range(N):
        for j in range(N):
            if (i, j) not in visited and board[i, j] != 0:
                group, visited = find_group(board, i, j, board[i, j], visited)
                group_liberties = count_liberties(board, group)
                # Adjust energy contribution based on stone color
                if board[i, j] == 1:  # White stones
                    energy_white += J_ally * len(group) - J_enemy * group_liberties
                elif board[i, j] == -1:  # Black stones
                    energy_black += J_ally * len(group) - J_enemy * group_liberties
    return energy_black, energy_white

# Function to calculate the Ising polynomial for the Go board configuration
def ising_polynomial(board, J_ally_sym, J_enemy_sym, stone, liberty):
    polynomial = 0
    for i in range(N):
        for j in range(N):
            if board[i, j] != 0:
                # Use symbolic variables to represent the energy contribution of each stone
                polynomial += J_ally_sym * stone[i, j] - J_enemy_sym * liberty[i, j]
    return polynomial

# Function to check the constraint (no group of stones can have zero liberties)
def check_constraints(board):
    constraints_met = True
    visited = set()
    for i in range(N):
        for j in range(N):
            if board[i, j] != 0 and (i, j) not in visited:
                group, visited = find_group(board, i, j, board[i, j], visited)
                if count_liberties(board, group) == 0:
                    constraints_met = False
                    break
    return constraints_met

# Example Go board configuration (1 for white, -1 for black, 0 for empty)
go_board[0, 0] = 1
go_board[0, 1] = -1
go_board[1, 0] = -1
go_board[1, 1] = 1
go_board[0, 3] = -1
go_board[3, 0] = -1
go_board[3, 3] = 1

# Calculate the energy of the sample configuration for black and white stones separately
energy_black, energy_white = go_energy(go_board, J_ally, J_enemy)
print(f"The energy of the black stones is: {energy_black}")
print(f"The energy of the white stones is: {energy_white}")

# Calculate the Ising polynomial of the sample configuration
ising_poly = ising_polynomial(go_board, J_ally_sym, J_enemy_sym, stone, liberty)
print(f"The Ising polynomial of the Go board configuration is: {ising_poly}")

# Check and print the constraints for the sample configuration
constraints_met = check_constraints(go_board)
print(f"Constraints met: {constraints_met}")

# Output the board to visualize the current state
print("Current board configuration:")
print(go_board)


The energy of the black stones is: 12
The energy of the white stones is: 9
The Ising polynomial of the Go board configuration is: J_ally*s[0, 0] + J_ally*s[0, 1] + J_ally*s[0, 3] + J_ally*s[1, 0] + J_ally*s[1, 1] + J_ally*s[3, 0] + J_ally*s[3, 3] - J_enemy*l[0, 0] - J_enemy*l[0, 1] - J_enemy*l[0, 3] - J_enemy*l[1, 0] - J_enemy*l[1, 1] - J_enemy*l[3, 0] - J_enemy*l[3, 3]
Constraints met: False
Current board configuration:
[[ 1 -1  0 -1  0]
 [-1  1  0  0  0]
 [ 0  0  0  0  0]
 [-1  0  0  1  0]
 [ 0  0  0  0  0]]


In [21]:
import numpy as np
import sympy as sp

# Constants from the Ising model adapted for Go
J_ally = 1    # Interaction strength between allied stones
J_enemy = -1   # Interaction strength between enemy stones

# Define symbolic variables for Ising polynomial
J_ally_sym, J_enemy_sym = sp.symbols('J_ally J_enemy')
stone = sp.IndexedBase('s')
liberty = sp.IndexedBase('l')

# Define the size of the Go board (standard is 19x19)
N = 13  # Go board size

# Initialize the Go board with zeros (empty board)
go_board = np.zeros((N, N), dtype=int)

# Helper function to find the group of stones connected to the stone at (i, j)
def find_group(board, i, j, color, visited):
    if (i, j) in visited or board[i, j] != color:
        return [], visited

    visited.add((i, j))
    group = [(i, j)]
    # Check adjacent positions for the same color stone and add to the group
    if i > 0:
        new_group, visited = find_group(board, i-1, j, color, visited)
        group.extend(new_group)
    if i < N-1:
        new_group, visited = find_group(board, i+1, j, color, visited)
        group.extend(new_group)
    if j > 0:
        new_group, visited = find_group(board, i, j-1, color, visited)
        group.extend(new_group)
    if j < N-1:
        new_group, visited = find_group(board, i, j+1, color, visited)
        group.extend(new_group)
    return group, visited

# Helper function to count liberties of a group of stones
def count_liberties(board, group):
    liberties = set()
    # Check adjacent positions for empty spaces and count them as liberties
    for i, j in group:
        if i > 0 and board[i-1, j] == 0:
            liberties.add((i-1, j))
        if i < N-1 and board[i+1, j] == 0:
            liberties.add((i+1, j))
        if j > 0 and board[i, j-1] == 0:
            liberties.add((i, j-1))
        if j < N-1 and board[i, j+1] == 0:
            liberties.add((i, j+1))
    return len(liberties)

# Function to calculate the energy of the Go board configuration for black and white stones separately
def go_energy(board, J_ally, J_enemy):
    energy_black = 0
    energy_white = 0
    visited = set()
    for i in range(N):
        for j in range(N):
            if (i, j) not in visited and board[i, j] != 0:
                group, visited = find_group(board, i, j, board[i, j], visited)
                group_liberties = count_liberties(board, group)
                # Adjust energy contribution based on stone color
                if board[i, j] == 1:  # White stones
                    energy_white += J_ally * len(group) - J_enemy * group_liberties
                elif board[i, j] == -1:  # Black stones
                    energy_black += J_ally * len(group) - J_enemy * group_liberties
    return energy_black, energy_white

# Function to calculate the Ising polynomial for the Go board configuration
def ising_polynomial(board, J_ally_sym, J_enemy_sym, stone, liberty):
    polynomial = 0
    for i in range(N):
        for j in range(N):
            if board[i, j] != 0:
                # Use symbolic variables to represent the energy contribution of each stone
                polynomial += J_ally_sym * stone[i, j] - J_enemy_sym * liberty[i, j]
    return polynomial

# Function to check the constraint (no group of stones can have zero liberties)
def check_constraints(board):
    constraints_met = True
    visited = set()
    for i in range(N):
        for j in range(N):
            if board[i, j] != 0 and (i, j) not in visited:
                group, visited = find_group(board, i, j, board[i, j], visited)
                if count_liberties(board, group) == 0:
                    constraints_met = False
                    break
    return constraints_met

# A valid Go board configuration where every stone has at least one liberty
# Example Go board configuration (1 for white, -1 for black, 0 for empty)
# Black stones
go_board[0, 0] = -1
go_board[0, 2] = -1
go_board[1, 1] = -1
go_board[2, 0] = -1

# White stones
go_board[0, 12] = 1
go_board[1, 11] = 1
go_board[2, 12] = 1
go_board[12, 0] = 1
go_board[11, 1] = 1
go_board[12, 2] = 1

# Calculate the energy of the sample configuration for black and white stones separately
energy_black, energy_white = go_energy(go_board, J_ally, J_enemy)
print(f"The energy of the black stones is: {energy_black}")
print(f"The energy of the white stones is: {energy_white}")

# Calculate the Ising polynomial of the sample configuration
ising_poly = ising_polynomial(go_board, J_ally_sym, J_enemy_sym, stone, liberty)
print(f"The Ising polynomial of the Go board configuration is: {ising_poly}")

# Check and print the constraints for the sample configuration
constraints_met = check_constraints(go_board)
print(f"Constraints met: {constraints_met}")

# Output the board to visualize the current state
print("Current board configuration:")
print(go_board)


The energy of the black stones is: 16
The energy of the white stones is: 24
The Ising polynomial of the Go board configuration is: J_ally*s[0, 0] + J_ally*s[0, 12] + J_ally*s[0, 2] + J_ally*s[1, 11] + J_ally*s[1, 1] + J_ally*s[11, 1] + J_ally*s[12, 0] + J_ally*s[12, 2] + J_ally*s[2, 0] + J_ally*s[2, 12] - J_enemy*l[0, 0] - J_enemy*l[0, 12] - J_enemy*l[0, 2] - J_enemy*l[1, 11] - J_enemy*l[1, 1] - J_enemy*l[11, 1] - J_enemy*l[12, 0] - J_enemy*l[12, 2] - J_enemy*l[2, 0] - J_enemy*l[2, 12]
Constraints met: True
Current board configuration:
[[-1  0 -1  0  0  0  0  0  0  0  0  0  1]
 [ 0 -1  0  0  0  0  0  0  0  0  0  1  0]
 [-1  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 